GLS_MAX_ITERATIONS = 2
GLS_LOCAL_SEARCH_STEPS = 50
GLS_CANDIDATES_PER_STEP = 15

GLS_ALPHA = 0.10
GLS_BETA = None

GLS_ACCEPTANCE_DROP_RATIO = 0.015
GLS_INTENSIFICATION_INTERVAL = 8
GLS_RESTART_AFTER = 100

MAX_SHIFT = 10

# GLS_MAX_ITERATIONS = 10
# GLS_LOCAL_SEARCH_STEPS = 15
# GLS_CANDIDATES_PER_STEP = 5

# GLS_ALPHA = 0.10
# GLS_BETA = None

# GLS_ACCEPTANCE_DROP_RATIO = 0.015
# GLS_INTENSIFICATION_INTERVAL = 8
# GLS_RESTART_AFTER = 40

# MAX_SHIFT = 10